### PR TITLE
If you want to add your project look here first.

### PR DESCRIPTION
**Pull request by Ashvin-Ranjan**
This is a PR to add more projects into `PROJECTS.md` without flooding `main` with meaningless commits, once you added your project(s) to `PROJECTS.md` on your own branch make a PR into this branch and when we get 25 I will merge this into `main`

Projects:
- [X] [discord.n](https://github.com/nbuilding/discord.n)
- [X] [N Libs](https://github.com/Ashvin-Ranjan/N-Libs)
- [X] [json extra](https://github.com/nbuilding/json-extra)
- [X] [ChessN't](https://github.com/Ashvin-Ranjan/chessN-t)
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None
- [ ] None

### CODE REVIEW

**Comment by SheepTester** [comment]
> without flooding `main` with meaningless commits

I don't think this is a problem

**Comment by Ashvin-Ranjan** [comment]
> > without flooding `main` with meaningless commits
> 
> I don't think this is a problem

I think it is though because it's not really that useful to have 25 random sporadic commits in an unorderly fashion.

**Comment by SheepTester** [comment]
Since these are changes to PROJECT.md, they won't affect the python/ folder, so the [commit history for the interpreter](https://github.com/nbuilding/N-lang/commits/main/python) won't be messy

**Comment by Ashvin-Ranjan** [comment]
I don't think anyone is just checking the commit history for the interpreter. Most people are going to look at `main`.

**Comment by SheepTester** [comment]
I mean, commit histories tend to be messy anyways, and when this is merged, their commits will still be interspersed based on their commit timestamp, I believe

**Comment by Ashvin-Ranjan** [comment]
True, but I also think this gives people a clear and correct way to get their projects into it without making a pr into `main` which some people outside of the N building group might not like to do.

**Comment by SheepTester** [comment]
It should be fine if we have instructions in the README; I feel like this PR is more obscure than the README

**Comment by Ashvin-Ranjan** [comment]
Sure I will merge this and create instructions in the readme

**Pull request merged**
