### PR TITLE
Fix async issue in executable

### LINKED ISSUE #70: Async does not work with N executable
This appears to only occur in the executable of N, as it is most likely a problem with `pyinstaller` or the tool I am using to create the executable

This does occur on Windows, but it is not confirmed yet whether it occurs on the Mac version too.

Here is the error readout
```
Traceback (most recent call last):
  File "n.py", line 123, in <module>
  File "asyncio\base_events.py", line 642, in run_until_complete
  File "n.py", line 101, in parse_tree
AttributeError: 'Cmd' object has no attribute 'eval'
[9760] Failed to execute script n
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Function.run.<locals>.run_command() running at function.py:35> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002339C7EAD30>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Function.run.<locals>.run_command() running at function.py:35> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x000002339CBC7970>()]>>
```

We have deduced that it is an error with the async as this occurred when testing [discord.n](https://github.com/nbuilding/discord.n), which is every async heavy.

### PR DESCRIPTION
**Pull request by SheepTester**
Fixes #70

I haven't tested this, so perhaps can @Ashvin-Ranjan test to see if this resolves the issue?

I just added

```py
multiprocessing.freeze_support()
```

per the linked wiki page in #70. I'm not sure if it works.

### CODE REVIEW

**Comment by Ashvin-Ranjan** [comment]
Ok. I will check out in a bit, but to test, I think #97 needs to get resolved because this seems to happen most with the `request` library.

**Comment by Ashvin-Ranjan** [comment]
This does not work yet, it still needs to be fixed as it gives the same error

**Comment by SheepTester** [comment]
Ok so the issue turned out to be because `cmd` is also the name of some built in [Python library](https://docs.python.org/3/library/cmd.html)

**Review by Ashvin-Ranjan — APPROVED** [review]
Looks Good!

**Pull request merged**
