### PR TITLE
Violently enforce PEP 8's recommended maximum line length of 79

### PR DESCRIPTION
**Pull request by SheepTester**
I also pip installed `autopep8`; you can make it autoformat all the files by doing

```sh
autopep8 --in-place --aggressive --aggressive **/*.py
```

(see changes in `README.md`, `requirements.txt`)

### CODE REVIEW

**Comment by Ashvin-Ranjan** [comment]
How do we continue to enforce this?

**Comment by SheepTester** [comment]
> How do we continue to enforce this?

If your editor is able to autoformat Python, you can use that feature

If not, you can pip install from the requirements.txt and then run the command in the PR description

**Comment by Ashvin-Ranjan** [comment]
Is there any sort of GitHub action or something we can use the autoformat everything and check for errors using `pylint`? That way we don't have to worry about forgetting it.

**Comment by SheepTester** [comment]
Will switch to black per recommendation of @ytchang05

**Pull request merged**
