### PR TITLE
Compile built-in functions and modules to JS

### PR DESCRIPTION
**Pull request by SheepTester**
- [ ] Built-in functions:
  - [x] `intInBase10`
  - [x] `round`
  - [x] `floor`
  - [x] `ceil`
  - [x] `charCode`
  - [x] `intCode`
  - [x] `charAt`
  - [x] `substring`
  - [x] `len`
  - [x] `split`
  - [x] `strip`
  - [x] `range` (See #246)
  - [x] `print`
    - [ ] Pretty `print`
  - [x] `itemAt`
  - [x] `append`
  - [x] `filterMap`
  - [x] `default`
  - [x] `then`
  - [x] `mapFrom`
  - [x] `getValue`
  - [x] `entries`

- [x] Built-in modules
  - [x] FileIO
    - [x] write
    - [x] append
    - [x] read
  - [x] json
    - [x] null
    - [x] string
    - [x] number
    - [x] boolean
    - [x] array
    - [x] object
    - [x] parse
    - [x] parseSafe (currently the same as parse because of the `maybe[()]` bug)
    - [x] stringify
  - [x] request
    - [x] post
    - [x] get
  - [x] SystemIO
    - [x] inp
  - [x] times
    - [x] sleep
  - [x] websocket
    - [x] connect

### CODE REVIEW

**Comment by SheepTester** [comment]
I would like to fix the `maybe[()]` bug (it affects `parseSafe`) and more importantly deal with functions with type variables

**Comment by SheepTester** [comment]
Say I have a function with type `[t] t -> list[t] -> list[t]` (eg `append`). When I do `append("hi")`, I know that `t` -> `str`; this substitution is accessible via `substitutions` in the compareAssignable context.

https://github.com/nbuilding/N-lang/blob/06c809acdaf354219a1071d036c85d0a72eda407/js/src/type-checker/types/comparisons/compare-assignable.ts#L310-L313

`append` should accept a "function type variable" (FTV) type value during runtime. Probably a string would look like `{ value: "hi", type: { type: "named", typeSpec: "str", typeVars: [] } }` or something.

But when I do `append("hi")`, I'm giving it a plain JS string, which is unacceptable.

Instead, I think it could try wrapping `append` in a function that converts its arguments to the happy FTV values it wants. For example,

```js
(function (item) {
  return function (list) {
    return append({ value: item, type: { type: "named", typeSpec: "str", typeVars: [] } })(list.map(function (item) {
      return { value: item, type: { type: "named", typeSpec: "str", typeVars: [] } }
    }).map(function (ftv) {
      return ftv.value;
    });
  };
})("hi", ["hello", "wow", "wee"]);
```

Probably the prelude would have to keep track of `str -> { toFtv, fromFtv }` functions because doing all that repeatedly would be quite verbose.

**Comment by SheepTester** [comment]
Hmm, I guess transforming between FTV is somewhat necessary because `maybe[()]` and `maybe[str]` are represented differently, so there isn't just one `maybe[t]`. Probably instead, `maybe[t]` will be represented differently (or the same as `maybe[str]`, as long as () is wrapped up nicely), which means there needs to be a conversion from () to t. That's doable; `{ type: 'unit' }` or whatever should suffice.

Otherwise, though, I don't think there's much of a need (except for `print`, will get to that later) for FTV conversions. Most values can stay the same; it's just unit-like values that will be troublesome.

Actually, can't FTV conversions just be reserved for unit-like values? Replace them with some dummy truthy value; a conversion back from FTV wouldn't even be necessary because unit-like values aren't used directly.

This should simplify the problem, hopefully! This allows `maybe[t]` to still be unambiguously represented as `T | undefined`. To ensure that unit-like values are still equal to each other, we could have a common variable `var unit_n = {};` or smth

Still, I think the transformation process isn't that trivial. After resolving t -> (), converting `list[()]` to `list[truthy ()]` would require some intelligence, and enum values containing () still need a lot of work since they could be structurally very different. Also, a transformation from FTV might still be necessary for enums containing a type variable

aiyaaiyaaiyaaiya

**Comment by SheepTester** [comment]
Say I have a `[t] int -> t -> list[t] -> str -> maybe[t] -> int -> char` hmm, I guess there's no point in just transforming the range of arguments that use the type variable since likely the type variable will be in the return type as well (`len` would be an exception), so the return value would probably have to be transformed anyways. Should be fine

Bug: Enums will probably be seen as arrays by `len`

**Comment by Ashvin-Ranjan** [comment]
> Say I have a `[t] int -> t -> list[t] -> str -> maybe[t] -> int -> char` hmm, I guess there's no point in just transforming the range of arguments that use the type variable since likely the type variable will be in the return type as well (`len` would be an exception), so the return value would probably have to be transformed anyways. Should be fine
> 
> Bug: Enums will probably be seen as arrays by `len`

@SheepTester, with the new internal traits update, this functionality can be avoided. Also what is stopping you from just using js `enum` syntax for enums

**Pull request merged**
