### PR TITLE
Bringing JS up to par

### PR DESCRIPTION
**Pull request by SheepTester**
Will add the new syntax and type checking

### CODE REVIEW

**Comment by SheepTester** [comment]
Deployed: [Check it out](https://nbuilding.github.io/N-lang/sean/)

**Comment by SheepTester** [comment]
TODO:

Ambiguous syntax:
```js
return 3
-1
```

This is valid, and `0.1` on its own is classified as a number:
```js
var main = [a: int] -> int : {
	print a
}
<main 0.1>
```

Tuples and chars?

**Comment by SheepTester** [comment]
[try it out](https://nbuilding.github.io/N-lang/sean/)

**Comment by Ashvin-Ranjan** [comment]
seems like gamer

**Pull request merged**
