### PR TITLE
Use pycharm pep8 formatter

### PR DESCRIPTION
**Pull request by saumyasinghal747**
I formatted everything using pycharm's nice formatter.

### CODE REVIEW

**Comment by Ashvin-Ranjan** [comment]
Please fix your formatter, it just changed every `	` to `  `, which shows up as a really big change to GitHub and will mess with our formatting.

**Review by Ashvin-Ranjan — CHANGES_REQUESTED** [review]
Please Fix the formatting for this.

**Comment by SheepTester** [comment]
> Please fix your formatter, it just changed every ` ` to ` `, which shows up as a really big change to GitHub and will mess with our formatting.

I disagree; I approve of this change. It changes the hard tabs to four spaces, which is proper per PEP8

**Comment by Ashvin-Ranjan** [comment]
> > Please fix your formatter, it just changed every to , which shows up as a really big change to GitHub and will mess with our formatting.
>
> I disagree; I approve of this change. It changes the hard tabs to four spaces, which is proper per PEP8

I disagree; I don't think this is the place that it should be done as there is a lot of noise in the PR because several files have been completely changed due to this and it makes it hard to sift through all of this. This should be in a different PR.

**Comment by Ashvin-Ranjan** [comment]
I retract my statement

**Review by Ashvin-Ranjan — COMMENTED** [review]
Ok, looks good, sorry for messing up what the pr was about.

**Review by Ashvin-Ranjan — APPROVED** [review]
eee, i forgot the aprove.

**Review by SheepTester — APPROVED** [review]
Might go through and more aggressively autoformat the files with this autopep8 thing I found but looks good to me!

**Pull request merged**
